### ISSUE TITLE
Broken link to CONTRIBUTING.md in components-dev/components/webcomponentsjs at master · basic-web-components/components-dev

### ISSUE THREAD

**Issue by anaran** [basic-web-components/components-dev#1]
See this link:

https://github.com/basic-web-components/components-dev/blob/master/components/webcomponentsjs/CONTRIBUTING.md

  referenced from

https://github.com/basic-web-components/components-dev/tree/master/components/webcomponentsjs

Details:

That link leads a 404:

See the [contributing guide] (https://github.com/basic-web-components/components-dev/blob/master/components/webcomponentsjs/CONTRIBUTING.md)

**Comment by JanMiksovsky** [comment]
@anaran: Thanks for your interest in contributing.

The repository you reference, webcomponentsjs, is actually a library produced by Google's [Polymer](http://polymer-project.org) group. The webcomponents.js library is used by Basic Web Components, but is maintained by Google at https://github.com/webcomponents/webcomponentsjs. If you're interested in contributing to webcomponents.js, you can see their Contribution Guide there.

If you're interested in contributing to Basic Web Components, we haven't put together our own guide for contributors yet — all we have a small [wiki](https://github.com/basic-web-components/components-dev/wiki) with a link to a coding style guide and a list of components we want help producing. We'd love any help you can offer! You can follow up with me directly at jan@component.kitchen if you have questions.
